name: Build and Deploy
on:
  push:
    branches:
      - TEST-*
      - develop
      - main
  pull_request:
    branches:
      - develop
      - TEST-*
      - main
jobs:
  setup_env:
    name: Setup environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.outputs.set_env.env}}
    steps:
      - id: set_env
        run: |
            if [[ ${{ github.ref == 'refs/heads/main' ]]; then
              echo "::set-output name=env::PROD"
            else 
              echo "::set-output name=env::DEV"
            fi
  build:
    name: TEST
    runs-on: ubuntu-latest
    needs: setup_env
    environment : ${{needs.setup_env.outputs.env_name}}
    steps:
       - name: Print ENV name
         run: |
          echo "SETUP UP ${{needs.setup_env.outputs.env_name}}";
          echo "environment secret ${{ secrets.NAME_OF_ENVIRONMENT }}"
