name: Build and Deploy
on:
  push:
    branches:
      - TEST-*
      - develop
      - main
  pull_request:
    branches:
      - develop
      - TEST-*
      - main
jobs:
  # setup_env:
  #   name: Setup environment
  #   runs-on: ubuntu-latest
  #   outputs:
  #     env_name: ${{ steps.outputs.set_env.env}}
  #   steps:
  #     - id: set_env
  #       run: |
  #           if [[ ${{ github.ref == 'refs/heads/main'}} ]]
  #             then echo "::set-output name=env::PROD'"
  #           else "::set-output name=env::DEV'"
  #           fi
  #     - name: Get ENV
  #       run: echo "The selected environment is ${{ steps.set_env.outputs.env }}"
  # build:
  #   name: TEST
  #   runs-on: ubuntu-latest
  #   needs: setup_env
  #   steps:
  #      - name: Print ENV name
  #        run: |
  #         echo "SETUP UP ${{needs.setup_env.outputs.env_name}}";
  #         echo "environment secret ${{ secrets.NAME_OF_ENVIRONMENT }}"
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.env }}
      output2: ${{ steps.step2.outputs.env }}
    steps:
    - id: step1
      run: |
        if [ ${{ github.ref = 'refs/heads/main'}} ]; then
          echo "::set-output name=env::PROD"
        else
          echo "::set-output name=env::DEV"
        fi
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
