name: Build and Deploy
on:
  push:
    branches:
      - TEST-*
      - develop
      - main
    tags:
      - v*
  pull_request:
    branches:
      - develop
      - TEST-*
      - main
jobs:
  setup_environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_env.outputs.env }}
    steps:
    - id: get_env
      run: |
        if [ ${{ github.ref }} = refs/heads/main ]; then
          echo "::set-output name=env::PROD"
        else
          echo "::set-output name=env::DEV"
        fi
    - id: print_env
      name: Print environment
      run: echo ${{ steps.get_env.outputs.env }}
  build:
    runs-on: ubuntu-latest
    needs: setup_environment
    environment: ${{needs.setup_environment.outputs.env_name}}
    steps:
    - run: echo ${{needs.setup_environment.outputs.env_name}}
    - run: echo ${{secrets.NAME_OF_ENVIRONMENT}}
  deploy:
    runs-on: ubuntu-latest
    needs: 
    - setup_environment
    - build
    environment: ${{needs.setup_environment.outputs.env_name}}
    steps:
    - run: echo Inside deploy ${{needs.setup_environment.outputs.env_name}}
    - run: echo ${{secrets.NAME_OF_ENVIRONMENT}}
    - run: echo Event name ${{ github.event_name }}
    - run: echo ${{github.ref}} 
