name: Build and Deploy
on:
  push:
    branches:
      - TEST-*
      - develop
      - main
  pull_request:
    branches:
      - develop
      - TEST-*
      - main
jobs:
  setup_env:
    name: Setup environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.outputs.env }}
    steps:
      - id: set_env
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: echo "::set-output name=env::DEV"
      - id: set_env1
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "::set-output name=env::PROD"

  build:
    name: TEST
    runs-on: ubuntu-latest
    needs: setup_env
    environment : ${{needs.setup_env.outputs.env }}
    steps:
       - name: Print ENV name
         run: |
          echo "SETUP UP ${{needs.setup_env.outputs.env}}";
          echo "environment secret ${{ secrets.NAME_OF_ENVIRONMENT }}"
